/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.94
 * Generated at: 2019-07-21 22:51:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <title> Formulaire candidat  </title>\r\n");
      out.write("        <link type=\"text/css\" rel=\"stylesheet\" href=\"inc/style.css\" />\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("   \r\n");
      out.write("        <div>\r\n");
      out.write("            <form method=\"get\" action=\"CreationCandidat\">\r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <h2> <legend> Informations personnelles</legend> </h2>\r\n");
      out.write("    \r\n");
      out.write("                    <label for=\"nomCandidat\">Nom <span class=\"requis\">*</span></label>\r\n");
      out.write("                    <input type=\"text\" id=\"nomCandidat\" name=\"nomCandidat\" value=\"\" size=\"20\" maxlength=\"20\" />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"prenomCandidat\">Prénom </label>\r\n");
      out.write("                    <input type=\"text\" id=\"prenomCandidat\" name=\"prenomCandidat\" value=\"\" size=\"20\" maxlength=\"20\" />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"cinCandidat\">CIN <span class=\"requis\">*</span></label>\r\n");
      out.write("                    <input type=\"text\" id=\"cinCandidat\" name=\"cinCandidat\" value=\"\" size=\"20\" maxlength=\"20\" />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"datedenaissance\">Date de naissance</label>\r\n");
      out.write("                    <input type=\"text\" id=\"datedenaissance\" name=\"datedenaissance\" value=\"\" size=\"20\" maxlength=\"20\" placeholder=\"jj-mm-aaaa\"/>\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("    \r\n");
      out.write("                    <label for=\"lieuCandidat\">Lieu de naissance  <span class=\"requis\">*</span></label>\r\n");
      out.write("                    <input type=\"text\" id=\"lieuCandidat\" name=\"lieuCandidat\" value=\"\" size=\"20\" maxlength=\"20\" />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("    \r\n");
      out.write("                   \r\n");
      out.write("                    <label for=\"professionactuel\">Profession Actuel </label>\r\n");
      out.write("                    <input type=\"diplome\" id=\"professionactuel\" name=\"professionactuel\" value=\"\" size=\"20\" maxlength=\"60\" />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    </fieldset>\r\n");
      out.write("                    \r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <h2> <legend> Adresse et Coordonées</legend> </h2>\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                    <label for=\"adresseCandidat\">Adresse  <span class=\"requis\">*</span></label>\r\n");
      out.write("                    <input type=\"text\" id=\"adresseCandidat\" name=\"adresseCandidat\" value=\"\" size=\"30\" maxlength=\"60\" />\r\n");
      out.write("                    \r\n");
      out.write("                    &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  \r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"emailCandidat\">Adresse email <span class=\"requis\">*</span></label>\r\n");
      out.write("                    <input type=\"email\" id=\"emailCandidat\" name=\"emailCandidat\" value=\"\" size=\"20\" maxlength=\"60\" />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"RegionCandidat\">Région <span class=\"requis\">*</span></label>\r\n");
      out.write("                    <select name=\"region\" size=\"\">\r\n");
      out.write(" \r\n");
      out.write(" \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 
					try{
					                                Class.forName("com.mysql.jdbc.Driver");
					                                
					                                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/formulaire","root",""); 
					                    
					                                PreparedStatement statement = cn.prepareStatement("select * from AdrsCord");
					                                ResultSet Rs = statement.executeQuery() ;
					                                while(Rs.next()){
					                                                String item= Rs.getString("Region");
					                                                
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t                        <option value=\"");
      out.print(item);
      out.write('"');
      out.write('>');
      out.print(item);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t                  ");
 
					                                        
					                    } 
					                    
					                    }
					catch (Exception e)
					{
					                                    System.out.print("impossible de se connecter à la base");
					                                    e.printStackTrace();
					                        
				    } 
      out.write("\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t                  \r\n");
      out.write("\t\t\t\t\t &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  \r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"CodepostalCandidat\">Code postal </label>\r\n");
      out.write("                    <input type=\"text\" id=\"CodepostalCandidat\" name=\"CodepostalCandidat\" value=\"\" size=\"20\" maxlength=\"20\" />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                     <label for=\"ProvinceCandidat\">Province </label>\r\n");
      out.write("                    <select name=\"province\" size=\"\">\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 
					try{
					                                Class.forName("com.mysql.jdbc.Driver");
					                                
					                                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/formulaire","root",""); 
					                    
					                                PreparedStatement statement = cn.prepareStatement("select * from AdrsCord ");
					                                
					                                ResultSet Rs = statement.executeQuery() ;
					                                while(Rs.next()){
					                                                String item= Rs.getString("Province");
					                                                
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t                        <option value=\"");
      out.print(item);
      out.write('"');
      out.write('>');
      out.print(item);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t                  ");
 
					                                        
					                    } 
					                    
					                    }
					catch (Exception e)
					{
					                                    System.out.print("impossible de se connecter à la base");
					                                    e.printStackTrace();
					                        
				    } 
      out.write("\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("                    &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  \r\n");
      out.write("                    \r\n");
      out.write("                     <label for=\"telephoneCandidat\">Numéro de téléphone <span class=\"requis\">*</span></label>\r\n");
      out.write("                    <input type=\"text\" id=\"telephoneCandidat\" name=\"telephoneCandidat\" value=\"\" size=\"20\" maxlength=\"20\" />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    \r\n");
      out.write("                     <label for=\"villeCandidat\">Ville <span class=\"requis\">*</span></label>\r\n");
      out.write("\t\t\t\t\t<select name=\"ville\" size=\"\">\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
 
					try{

					                                Class.forName("com.mysql.jdbc.Driver");
					                                
					                                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/formulaire","root",""); 
					                    
					                                PreparedStatement statement = cn.prepareStatement("select * from AdrsCord  ");
					                                ResultSet Rs = statement.executeQuery() ;
					                                while(Rs.next()){
					                                                String item= Rs.getString("Ville");
					                                                
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t                        <option value=\"");
      out.print(item);
      out.write('"');
      out.write('>');
      out.print(item);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t                  ");
 
					                                        
					                    } 
					                    
					                    }
					catch (Exception e)
					{
					                                    System.out.print("impossible de se connecter à la base");
					                                    e.printStackTrace();
					                        
				    } 
      out.write("\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t</select>                    &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  \r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"telephoneCandidat2\"> Téléphone 2 </label>\r\n");
      out.write("                    <input type=\"text\" id=\"telephoneCandidat2\" name=\"telephoneCandidat2\" value=\"\" size=\"20\" maxlength=\"20\" />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("     \r\n");
      out.write("                </fieldset>\r\n");
      out.write("                <fieldset>\r\n");
      out.write("                    <h2> <legend> Diplome</legend> </h2>\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                    <label for=\"paysCandidat\">Pays  <span class=\"requis\">*</span></label>\r\n");
      out.write("\t\t\t\t\t<select name=\"pays\" size=\"\"> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"Maroc\">Maroc</option>\r\n");
      out.write("\t\t\t\t    <option value=\"France\">France</option>\r\n");
      out.write("\t\t\t\t    <option value=\"Canada\">Canada</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t                   \r\n");
      out.write("                    &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  \r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"obtentionCandidat\">Année d'obtention<span class=\"requis\">*</span></label>\r\n");
      out.write("                    <input type=\"text\" id=\"obtentionCandidat\" name=\"obtentionCandidat\" value=\"\" size=\"20\" maxlength=\"60\" />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("           \r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"diplomeCandidat\">Diplome obtenu <span class=\"requis\">*</span></label>\r\n");
      out.write("\t\t\t\t\t<select name=\"diplome\" size=\"\"> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"Diplome d'Ingenieur d'Etat\">Diplome d'Ingenieur d'Etat</option>\r\n");
      out.write("\t\t\t\t    <option value=\"Diplome de technicien specialisé\">Diplome de technicien specialisé</option>\r\n");
      out.write("\t\t\t\t    <option value=\"Diplome d'economiste\">Diplome d'economiste</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"specialiteCandidat\">Specialité<span class=\"requis\">*</span></label>\r\n");
      out.write("\t\t\t\t\t<select name=\"specialite\" size=\"\"> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"Ingenieur des systemes d'informations\">Ingenieur des systemes d'informations</option>\r\n");
      out.write("\t\t\t\t    <option value=\"expert en finances\">expert en finances</option>\r\n");
      out.write("\t\t\t\t    <option value=\"technicien electrique\">technicien electrique </option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    \r\n");
      out.write("                    <label for=\"etablissementCandidat\">Etablissement <span class=\"requis\">*</span></label>\r\n");
      out.write("\t\t\t\t\t<select name=\"etablissement\" size=\"\"> \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"emi\">EMI</option>\r\n");
      out.write("\t\t\t\t    <option value=\"encg\">ENCG</option>\r\n");
      out.write("\t\t\t\t    <option value=\"bts\">BTS</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("                    <br />\r\n");
      out.write("                    <br />\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    </fieldset>\r\n");
      out.write("                    \r\n");
      out.write("                <input type=\"submit\" value=\"Valider\"  />\r\n");
      out.write("                <input type=\"reset\" value=\"Remettre à zéro\" /> <br />\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
